<a href="https://colab.research.google.com/github/Alamein/ArewaDS-Deep-Learning/blob/main/week_001/DL_exercise_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Arewa Data Science Academy**

### **Deep Learning Cohort1.0**

### **Name: Aminu Hamza Nababa**

### **Email: alaminhnab4@gmail.com**

### **Title: Week 1 Solution**

### **Exercises Solution**

1. Create a random tensor with shape (7, 7).

In [3]:
# 1
import torch

# crt random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.1290, 0.0942, 0.2571, 0.4599, 0.7504, 0.2432, 0.1291],
         [0.3229, 0.1035, 0.4086, 0.1372, 0.5456, 0.6709, 0.4707],
         [0.0881, 0.7634, 0.7649, 0.6903, 0.8070, 0.3696, 0.6248],
         [0.6214, 0.3284, 0.5429, 0.5165, 0.1296, 0.8755, 0.1751],
         [0.9878, 0.1393, 0.6006, 0.3440, 0.6009, 0.1054, 0.7379],
         [0.0115, 0.7817, 0.3779, 0.2363, 0.6360, 0.8848, 0.5039],
         [0.9324, 0.3465, 0.4234, 0.6071, 0.9618, 0.9405, 0.5214]]),
 torch.Size([7, 7]))

2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [5]:
Y = torch.rand(size=(1, 7))
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.1223],
         [1.7293],
         [2.4358],
         [1.8221],
         [2.4466],
         [1.9645],
         [2.7820]]),
 torch.Size([7, 1]))

3. Set the random seed to 0 and do 2 & 3 over again.

In [6]:
# manual seed setting
torch.manual_seed(0)

# Crtng two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?

In [7]:
# random seed on the GPU
torch.cuda.manual_seed(1234)

5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [9]:
# st random seed
torch.manual_seed(1234)

# Chck for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Crt 2 random tensors on GPU
tensor_A = torch.rand(size = (2,3)).to(device)
tensor_B = torch.rand(size = (2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [10]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

7. Find the maximum and minimum values of the output of 7.

In [11]:
# max
max = torch.max(tensor_C)

# min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

8. Find the maximum and minimum index values of the output of 7.

In [12]:
# arg max
arg_max = torch.argmax(tensor_C)

# arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [13]:
# st seed
torch.manual_seed(7)

# Crt random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Rmv single dimensions
tensor_E = tensor_D.squeeze()

# Prnt out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


10. Exercise 1 is not a coding base execise, it is reading exercise